name: Bluesky Autoposter - bskypromo

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install atproto

      - name: Run autoposter
        env:
          BSKY_USERNAME_BP: ${{ secrets.BSKY_USERNAME_BP }}
          BSKY_PASSWORD_BP: ${{ secrets.BSKY_PASSWORD_BP }}
        run: |
          python autoposter_bp.py
